### PR TITLE
Updating to Tailwind CSS 2.0.1

### PR DESCRIPTION
**Pull request by chkilel**
Because of compatibility reasons, I removed tailwindcss/typography, can be restored when Laravel-mix updates its dependencies to postcss ^8 (because of postcss-loader).

### CODE REVIEW

**Comment by cjkpl** [comment]
Hi @chkilel ,
Thanks for your update.

Let me ask you - why do you suggest that "typography" is not compatible with Tailwind 2.0? I've run it successfully, no issues at all.

**Comment by chkilel** [comment]
Hi @cjkpl,
Strange, when I was updating the theme, it didn't work for me.
You're right, it's running for me too.
I'll make a new PR later in the day.
Thanks.

**Comment by chkilel** [comment]
Hi @cjkpl,
I restored tailwindcss/typography and updated the README.
Thanks

**Comment by cjkpl** [comment]
Hi @chkilel,
Thanks for all your updates and bug fixes!

**Pull request merged**
